apiVersion: v1
kind: Service
metadata:
  name: my-microservice-service
spec:
  selector:
    app: my-microservice
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
